import type { Metadata } from "next";
import { PageShell } from "../site-components";
import { InquiryForm } from "./inquiry-form";
import { pageMetadata, setting } from "../../lib/public-cms";
import { editorPage } from "../../lib/editor-page";
import { VisualEditor } from "../visual-editor";
export async function generateMetadata():Promise<Metadata>{return pageMetadata("contact","Réserver / Contact","Parlez à Divine Motion de votre mariage, shooting, anniversaire ou projet photo et vidéo.")}
export const dynamic="force-dynamic";
const defaults={eyebrow:"Réserver · Contact",title:"Racontez-nous votre histoire.",intro:"Chaque projet est différent. Donnez-nous quelques détails et nous reviendrons vers vous avec les options les plus adaptées.",asideTitle:"Une première conversation",asideText:"Choisissez le type de projet : le formulaire s’adaptera pour ne vous demander que les renseignements utiles.",zoneLabel:"Zone principale",zone:"Québec · Ottawa",travelLabel:"Déplacements",travel:"Disponible pour voyager",sectionOrder:["contact-form"],hiddenSections:[],customSections:[]};
type Props={searchParams:Promise<{preview?:string}>};
export default async function Contact({searchParams}:Props){const query=await searchParams,stored=await setting("contact",defaults),general=await setting("general",{}),state=await editorPage("contact",{...defaults,...stored,general},query.preview==="1"),contact=state.content;return <PageShell general={contact.general}><div className={state.edit?"visual-editing":""}><section className="contact-hero page-hero dark-page" data-section-key="contact-hero"><div className="wrap"><p className="eyebrow light" data-edit-key="eyebrow">{contact.eyebrow}</p><h1 data-edit-key="title">{contact.title}</h1><p data-edit-key="intro">{contact.intro}</p></div></section><section className="contact-section section wrap" data-section-key="contact-form"><aside><p className="section-index" data-edit-key="asideTitle">{contact.asideTitle}</p><p data-edit-key="asideText">{contact.asideText}</p><div><span data-edit-key="zoneLabel">{contact.zoneLabel}</span><b data-edit-key="zone">{contact.zone}</b></div><div><span data-edit-key="travelLabel">{contact.travelLabel}</span><b data-edit-key="travel">{contact.travel}</b></div></aside><InquiryForm/></section></div>{state.user&&(state.edit||state.preview)&&<VisualEditor pageKey="contact" initial={contact} media={state.media} preview={state.preview} editUrl="/contact" previewUrl="/contact?preview=1"/>}</PageShell>}
