import type { Metadata } from "next";
import { PageShell } from "../site-components";
import { InquiryForm } from "./inquiry-form";
import { pageMetadata, setting } from "../../lib/public-cms";
export async function generateMetadata():Promise<Metadata>{return pageMetadata("contact","Réserver / Contact","Parlez à Divine Motion de votre mariage, shooting, anniversaire ou projet photo et vidéo.")}
export const dynamic="force-dynamic";
export const contactDefaults={eyebrow:"Réserver · Contact",title:"Racontez-nous votre histoire.",intro:"Chaque projet est différent. Donnez-nous quelques détails et nous reviendrons vers vous avec les options les plus adaptées.",asideTitle:"Une première conversation",asideText:"Choisissez le type de projet : le formulaire s’adaptera pour ne vous demander que les renseignements utiles.",zoneLabel:"Zone principale",zone:"Québec · Ottawa",travelLabel:"Déplacements",travel:"Disponible pour voyager",sectionOrder:["contact-form"],hiddenSections:[],customSections:[]};
export async function loadContactPublished(){const stored=await setting("contact",contactDefaults),general=await setting("general",{});return {...contactDefaults,...stored,general}}
export function ContactBody({contact,editable=false,editBasePath}:{contact:Record<string,any>;editable?:boolean;editBasePath?:string}){const ea=(a:Record<string,string>)=>editable?a:{};return <PageShell general={contact.general} editable={editable} editBasePath={editBasePath}><div className={editable?"visual-editing":""}><section className="contact-hero page-hero dark-page" {...ea({"data-section-key":"contact-hero"})}><div className="wrap"><p className="eyebrow light" {...ea({"data-edit-key":"eyebrow"})}>{contact.eyebrow}</p><h1 {...ea({"data-edit-key":"title"})}>{contact.title}</h1><p {...ea({"data-edit-key":"intro"})}>{contact.intro}</p></div></section><section className="contact-section section wrap" {...ea({"data-section-key":"contact-form"})}><aside><p className="section-index" {...ea({"data-edit-key":"asideTitle"})}>{contact.asideTitle}</p><p {...ea({"data-edit-key":"asideText"})}>{contact.asideText}</p><div><span {...ea({"data-edit-key":"zoneLabel"})}>{contact.zoneLabel}</span><b {...ea({"data-edit-key":"zone"})}>{contact.zone}</b></div><div><span {...ea({"data-edit-key":"travelLabel"})}>{contact.travelLabel}</span><b {...ea({"data-edit-key":"travel"})}>{contact.travel}</b></div></aside><InquiryForm/></section></div></PageShell>}
export default async function Contact(){const contact=await loadContactPublished();return <ContactBody contact={contact}/>}
