"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { MediaItem, MediaPicker, MediaThumb, VisualMediaField } from "./media-picker";
import { normalizeMediaList } from "../../lib/media-normalize";
type Item=Record<string,any>;const categories=["Mariage","Shooting urbain","Portrait","Couple","Anniversaire","Événement privé","Projet professionnel","Autre"],chapterNames=["Préparatifs","Cérémonie","Couple","Portraits","Famille","Proches","Réception","Détails","Soirée","Film","Autre"];
export function ProjectsManager({items,media,refresh,notice}:{items:Item[];media:MediaItem[];refresh:()=>void;notice:(message:string)=>void}){const [editing,setEditing]=useState<Item|null>(null),[query,setQuery]=useState("");const filtered=items.filter(item=>!query||`${item.title} ${item.people_names} ${item.category}`.toLowerCase().includes(query.toLowerCase()));if(editing)return <ProjectEditor initial={editing} media={media} close={()=>setEditing(null)} saved={()=>{setEditing(null);refresh()}} notice={notice}/>;return <section><div className="dm-page-title"><div><p className="dm-kicker">Divine Motion CMS</p><h1>Projets</h1><span>Mariages, shootings, portraits et événements.</span></div><button className="dm-primary" onClick={()=>setEditing(newProject())}>＋ Ajouter un projet</button></div><div className="dm-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher un projet…"/></div><div className="dm-table"><div className="dm-table-head"><span>Projet</span><span>Catégorie</span><span>Statut</span><span>Modifié</span><span/></div>{filtered.map(item=><button className="dm-table-row" key={item.id} onClick={()=>setEditing(normalize(item))}><span><b>{item.title}</b><small>{item.people_names||item.location||"Sans précision"}</small></span><span>{item.category}</span><span><Status value={item.status}/></span><span>{date(item.updated_at)}</span><span>›</span></button>)}{!filtered.length&&<Empty text="Aucun projet. Créez votre première histoire."/>}</div></section>}
function ProjectEditor({initial,media,close,saved,notice}:{initial:Item;media:MediaItem[];close:()=>void;saved:()=>void;notice:(message:string)=>void}){const [form,setForm]=useState(initial),[tab,setTab]=useState("content"),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[picker,setPicker]=useState<null|"gallery"|number>(null),[confirmPublish,setConfirmPublish]=useState(false),drag=useRef<number|null>(null);const gallery=useMemo(()=>normalizeMediaList(form.gallery,{includeHidden:true}),[form.gallery]);function change(key:string,value:any){setForm((old:Item)=>({...old,[key]:value}));setDirty(true)}useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave)},[dirty]);useEffect(()=>{if(!dirty||!form.id)return;const timer=window.setTimeout(()=>save(undefined,true),2500);return()=>clearTimeout(timer)},[form,dirty]);
async function save(status?:string,automatic=false){setSaving(true);try{const next={...form,status:status||form.status,gallery:gallery};const response=await fetch("/api/admin/cms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resource:"project",item:next})}),json=await response.json();if(!response.ok)throw new Error(json.error||"Enregistrement impossible");setForm({...next,id:json.id,slug:json.slug});setDirty(false);if(!automatic)notice(status==="published"?"Projet publié":status==="draft"?"Projet dépublié":"Brouillon enregistré");return json}catch(error){notice(error instanceof Error?error.message:"Erreur")}finally{setSaving(false)}}
async function publish(){await save("published");setConfirmPublish(false);saved()}async function unpublish(){if(!confirm("Dépublier ce projet ? Il restera disponible dans l’administration."))return;await save("draft")}
function setGallery(next:any[]){change("gallery",next)}function move(from:number,to:number){const next=[...gallery],entry=next.splice(from,1)[0];next.splice(to,0,entry);setGallery(next)}function add(ids:number[]){const existing=new Set(gallery.map(item=>item.id));setGallery([...gallery,...ids.filter(id=>!existing.has(id)).map(id=>({id,hidden:false,caption:"",alt:""}))]);setPicker(null)}
if(!form.category)return <section><PageHead title="Nouveau projet" subtitle="Étape 1 sur 2 · Choisissez le type de projet"/><div className="dm-project-types">{categories.map(category=><button key={category} onClick={()=>change("category",category)}><span>{category==="Mariage"?"♥":"◇"}</span><b>{category}</b></button>)}</div><button className="dm-secondary" onClick={close}>Annuler</button></section>;
return <section><PageHead title={form.id?form.title||"Modifier le projet":"Nouveau projet"} subtitle={`${form.category} · ${dirty?"Modifications non enregistrées":"Toutes les modifications sont enregistrées"}`}/><div className="dm-tabs">{[["content","Contenu"],["gallery","Galerie"],["chapters","Chapitres"],["video","Vidéo"],["seo","SEO & publication"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
{tab==="content"&&<div className="dm-editor-grid"><div className="dm-panel"><Field label="Titre du projet" value={form.title} onChange={value=>change("title",value)}/><Field label="Noms" value={form.peopleNames} onChange={value=>change("peopleNames",value)}/><div className="dm-two"><Select label="Catégorie" value={form.category} options={categories} onChange={value=>change("category",value)}/><Field label="Date" type="date" value={form.projectDate} onChange={value=>change("projectDate",value)}/></div><Field label="Lieu" value={form.location} onChange={value=>change("location",value)}/><Field label="Description courte" area value={form.excerpt} onChange={value=>change("excerpt",value)}/><Field label="Description longue" area value={form.description} onChange={value=>change("description",value)}/></div><div className="dm-panel"><VisualMediaField label="Photo de couverture" value={form.coverMediaId} media={media} onChange={value=>change("coverMediaId",value)}/><Field label="Mots-clés, séparés par des virgules" value={(form.tags||[]).join(", ")} onChange={value=>change("tags",value.split(",").map(x=>x.trim()).filter(Boolean))}/><Field label="Ordre d’affichage" type="number" value={form.displayOrder} onChange={value=>change("displayOrder",Number(value))}/></div></div>}
{tab==="gallery"&&<div className="dm-panel"><div className="dm-panel-title"><div><h2>Galerie du projet</h2><p>Sélectionnez plusieurs photos, puis glissez-les pour définir le récit.</p></div><button className="dm-primary" onClick={()=>setPicker("gallery")}>＋ Ajouter des médias</button></div><div className="dm-gallery-sort dm-gallery-pro">{gallery.map((entry,index)=>{const item=media.find(value=>value.id===entry.id);return <article className={entry.hidden?"hidden":""} draggable onDragStart={()=>drag.current=index} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(drag.current!==null)move(drag.current,index)}} key={`${entry.id}-${index}`}><div><MediaThumb item={item||{id:entry.id,type:"image",name:"Média"}}/><i>⋮⋮</i>{form.coverMediaId===entry.id&&<b>Couverture</b>}</div><small>{item?.title||item?.name||`Média ${entry.id}`}</small><div className="dm-gallery-actions"><button onClick={()=>change("coverMediaId",entry.id)}>Couverture</button><button onClick={()=>{const next=[...gallery];next[index]={...entry,hidden:!entry.hidden};setGallery(next)}}>{entry.hidden?"Afficher":"Masquer"}</button><button onClick={()=>setGallery(gallery.filter((_,i)=>i!==index))}>Retirer</button></div><details><summary>Légende et texte alternatif</summary><Field label="Légende" value={entry.caption||""} onChange={value=>{const next=[...gallery];next[index]={...entry,caption:value};setGallery(next)}}/><Field label="Texte alternatif" value={entry.alt||""} onChange={value=>{const next=[...gallery];next[index]={...entry,alt:value};setGallery(next)}}/></details></article>})}{!gallery.length&&<Empty text="Ajoutez jusqu’à plusieurs dizaines de photos en une seule sélection."/>}</div></div>}
{tab==="chapters"&&<div className="dm-panel"><div className="dm-panel-title"><div><h2>{form.category==="Mariage"?"Chapitres du mariage":"Séquences du projet"}</h2><p>Activez, ordonnez et illustrez les séquences utiles.</p></div></div><div className="dm-section-list dm-chapters">{(form.sections||[]).map((section:Item,index:number)=><article draggable onDragStart={()=>drag.current=index} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(drag.current===null)return;const next=[...form.sections],entry=next.splice(drag.current,1)[0];next.splice(index,0,entry);change("sections",next)}} key={`${section.sectionKey}-${index}`}><div className="dm-chapter-grip">⋮⋮</div><Toggle label={section.sectionKey} checked={section.enabled} onChange={value=>updateSection(index,{enabled:value})}/><Field label="Titre" value={section.title} onChange={value=>updateSection(index,{title:value})}/><Field label="Introduction" area value={section.intro} onChange={value=>updateSection(index,{intro:value})}/><button className="dm-choose-media" onClick={()=>setPicker(index)}>Galerie · {(section.media||[]).length} média{(section.media||[]).length>1?"s":""}</button></article>)}</div></div>}
{tab==="video"&&<div className="dm-panel"><h2>Vidéo du projet</h2><p>Choisissez un média vidéo ou utilisez une URL externe déjà enregistrée dans la médiathèque.</p><VisualMediaField label="Film ou teaser" value={form.videos?.[0]?.mediaId} media={media} accept={["video","external_video"]} onChange={value=>change("videos",value?[{...(form.videos?.[0]||{}),mediaId:value}]:[])}/><VisualMediaField label="Miniature personnalisée" value={form.videos?.[0]?.thumbnailMediaId} media={media} onChange={value=>change("videos",[{...(form.videos?.[0]||{}),thumbnailMediaId:value}])}/></div>}
{tab==="seo"&&<div className="dm-editor-grid"><div className="dm-panel"><Field label="Slug URL" value={form.slug} onChange={value=>change("slug",value)}/><Field label="SEO title" value={form.seoTitle} onChange={value=>change("seoTitle",value)}/><Field label="Meta description" area value={form.seoDescription} onChange={value=>change("seoDescription",value)}/><VisualMediaField label="Image de partage" value={form.seoImageMediaId} media={media} onChange={value=>change("seoImageMediaId",value)}/><div className="dm-seo-preview"><small>Aperçu Google</small><b>{form.seoTitle||form.title||"Titre de la page"}</b><span>divine-motion…/projets/{form.slug||"votre-projet"}</span><p>{form.seoDescription||form.excerpt||"Ajoutez une description claire pour les moteurs de recherche."}</p></div></div><div className="dm-panel"><Select label="Statut" value={form.status} options={["draft","published","archived"]} labels={["Brouillon","Publié","Archivé"]} onChange={value=>change("status",value)}/><Toggle label="Visible" checked={Boolean(form.visible)} onChange={value=>change("visible",value)}/><Toggle label="Projet mis en avant" checked={Boolean(form.featured)} onChange={value=>change("featured",value)}/><Status value={form.status}/></div></div>}
<div className="dm-editor-actions"><button className="dm-secondary" onClick={()=>{if(!dirty||confirm("Quitter sans enregistrer ?"))close()}}>Fermer</button><button className="dm-save" disabled={!dirty||saving} onClick={()=>save()}>Enregistrer le brouillon</button><a className={form.slug?"dm-secondary":"dm-secondary disabled"} href={form.slug?`/projets/${form.slug}?edit=1`:"#"} target="_blank">Modifier visuellement</a><a className={form.slug?"dm-secondary":"dm-secondary disabled"} href={form.slug?`/projets/${form.slug}?preview=1`:"#"} target="_blank">Prévisualiser</a>{form.status==="published"?<button className="dm-secondary" onClick={unpublish}>Dépublier</button>:<button className="dm-primary" disabled={!form.title||saving} onClick={()=>setConfirmPublish(true)}>Publier</button>}</div>{picker!==null&&<MediaPicker media={media} multiple initial={picker==="gallery"?gallery.map(entry=>entry.id):(form.sections[picker]?.media||[]).map((entry:any)=>Number(typeof entry==="object"?entry.id:entry))} close={()=>setPicker(null)} confirm={ids=>{if(picker==="gallery")add(ids);else{updateSection(picker,{media:ids.map(id=>({id,hidden:false,caption:"",alt:""}))});setPicker(null)}}}/>} {confirmPublish&&<Confirm title="Publier maintenant ?" close={()=>setConfirmPublish(false)} confirm={publish}><p><b>{form.peopleNames||form.title}</b></p><p>{form.projectDate||"Date non précisée"} · {form.category}</p><p>{gallery.length} média{gallery.length>1?"s":""} dans la galerie</p></Confirm>}</section>;
function updateSection(index:number,patch:Item){const next=[...form.sections];next[index]={...next[index],...patch};change("sections",next)}}
function PageHead({title,subtitle}:{title:string;subtitle:string}){return <div className="dm-page-title"><div><p className="dm-kicker">Divine Motion CMS</p><h1>{title}</h1><span>{subtitle}</span></div></div>}
function Confirm({title,children,close,confirm}:{title:string;children:React.ReactNode;close:()=>void;confirm:()=>void}){return <div className="dm-modal-backdrop"><div className="dm-confirm"><h2>{title}</h2>{children}<div className="dm-actions"><button className="dm-secondary" onClick={close}>Annuler</button><button className="dm-primary" onClick={confirm}>Confirmer la publication</button></div></div></div>}
function Field({label,value,onChange,type="text",area=false}:{label:string;value:any;onChange:(value:string)=>void;type?:string;area?:boolean}){return <label className="dm-field"><span>{label}</span>{area?<textarea rows={5} value={value??""} onChange={event=>onChange(event.target.value)}/>:<input type={type} value={value??""} onChange={event=>onChange(event.target.value)}/>}</label>}
function Select({label,value,options,labels,onChange}:{label:string;value:string;options:string[];labels?:string[];onChange:(value:string)=>void}){return <label className="dm-field"><span>{label}</span><select value={value||options[0]} onChange={event=>onChange(event.target.value)}>{options.map((option,index)=><option value={option} key={option}>{labels?.[index]||option}</option>)}</select></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="dm-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
function Status({value}:{value:string}){const labels:Record<string,string>={draft:"Brouillon",published:"Publié",archived:"Archivé"};return <i className={`dm-status ${value}`}>{labels[value]||value}</i>}
function Empty({text}:{text:string}){return <div className="dm-empty"><span>◇</span><p>{text}</p></div>}
function date(value:string){return value?new Intl.DateTimeFormat("fr-CA",{dateStyle:"medium"}).format(new Date(`${value}Z`)):"—"}
// normalizeGallery vivait ici en double (voir aussi app/visual-editor.tsx et
// lib/public-cms.ts) et ne filtrait pas les entrées invalides (`null` restait
// sans id, cf. AUDIT_DIVINE_MOTION.md). Remplacé par lib/media-normalize.ts.
function newProject(){return {title:"",peopleNames:"",slug:"",category:"",projectDate:"",location:"",excerpt:"",description:"",coverMediaId:null,gallery:[],videos:[],tags:[],seoTitle:"",seoDescription:"",seoImageMediaId:null,status:"draft",visible:true,featured:false,displayOrder:0,sections:chapterNames.map((title,index)=>({sectionKey:title,title,intro:"",media:[],videos:[],enabled:index<6,displayOrder:index}))}}
function normalize(item:Item){return {...newProject(),...item,peopleNames:item.people_names,projectDate:item.project_date,coverMediaId:item.cover_media_id,seoTitle:item.seo_title,seoDescription:item.seo_description,seoImageMediaId:item.seo_image_media_id,displayOrder:item.display_order,visible:Boolean(item.visible),featured:Boolean(item.featured),gallery:normalizeMediaList(item.gallery,{includeHidden:true})}}
