import Link from "next/link";
import type { Metadata } from "next";
import { Footer, Header, MediaPlaceholder, ServiceCard } from "./site-components";
import { displayDate, mediaUrl, pageMetadata, publishedProjects, setting } from "../lib/public-cms";
import { getAuthorizedAdmin } from "../lib/admin-auth";
import { getEditorState } from "../lib/editor-session";
import { db } from "../lib/cms-db";
import { visualContent } from "../lib/visual-editor";
import { VisualEditor } from "./visual-editor";

export const dynamic="force-dynamic";
export async function generateMetadata():Promise<Metadata>{return pageMetadata("home","Divine Motion | Photographie & Vidéographie","Divine Motion raconte vos histoires à travers la photographie et la vidéographie : mariages, portraits, shootings et événements.")}
const defaultOrder=["manifest","gallery","services","featured","film","approach","beyond","final"];
const homeDefaults={heroType:"image",heroTitle:"Des histoires vraies. Des émotions intactes.",heroSubtitle:"Photographie & vidéographie pour préserver les moments que vous avez vécus — et ceux qui vous ont échappé.",heroMediaId:null as number|null,heroMobileMediaId:null as number|null,heroFallbackMediaId:null as number|null,heroThumbnailMediaId:null as number|null,heroOverlay:58,heroPosition:"center center",heroVisible:true,cta1:"Découvrir notre travail",cta1Url:"/notre-travail",cta2:"Vérifier notre disponibilité",cta2Url:"/contact",manifestTitle:"Votre journée passe vite. Vos souvenirs ne devraient pas.",manifestText:"Les regards échangés, les éclats de rire, les gestes discrets et les émotions inattendues font partie de ces moments qui passent parfois en quelques secondes. Divine Motion est là pour les préserver et vous permettre de les revivre.",gallery:[] as number[],featuredProjectId:null as number|null,approachTitle:"Présents quand il le faut. Discrets quand il le faut.",approachText:"Notre approche privilégie les moments naturels. Nous vous guidons lorsque c’est nécessaire, puis nous laissons l’histoire se dérouler afin de capturer les émotions telles qu’elles existent réellement.",principles:[{title:"Observer",text:"Remarquer les détails, les interactions et les moments qui passent parfois inaperçus."},{title:"Raconter",text:"Créer une histoire cohérente plutôt qu’une simple succession d’images."},{title:"Préserver",text:"Transformer des instants en souvenirs capables de traverser les années."}],sectionOrder:defaultOrder,hiddenSections:[] as string[],sectionSettings:{} as Record<string,any>,customSections:[] as Array<Record<string,any>>};
const homeExtendedDefaults={...homeDefaults,servicesHeading:"Une histoire. Plusieurs façons de la revivre.",servicesIntro:"Le mariage est au cœur de notre univers. La photographie saisit l’instant; le film en conserve le mouvement, la voix et l’atmosphère.",services:[{title:"Photographie",text:"Des images naturelles et élégantes pensées pour raconter une journée dans son ensemble, jusque dans les détails que l’on remarque parfois seulement après.",cta:"Découvrir",href:"/services"},{title:"Vidéographie",text:"Des films qui redonnent vie aux voix, aux mouvements, à l’atmosphère et aux émotions.",cta:"Découvrir",href:"/services"},{title:"Photo + Vidéo",text:"Deux regards complémentaires pour raconter une même histoire de manière cohérente et complète.",cta:"Découvrir",href:"/services"}],featuredLabel:"Histoire à la une",featuredFallbackText:"Une journée remplie d’émotion, de foi, de famille et de célébration.",filmTitle:"Certaines émotions méritent plus qu’une photographie.",filmCta:"Voir le film",filmCtaUrl:"/notre-travail#film",beyondTitle:"Au-delà du mariage",beyondText:"Chaque histoire ne commence pas devant un autel. Divine Motion accompagne également les portraits, shootings créatifs, anniversaires et autres moments que vous souhaitez transformer en souvenirs.",beyondItems:[{title:"Portraits & shootings",text:"Shooting urbain · portrait · lifestyle · couple · projet créatif."},{title:"Anniversaires & événements",text:"Anniversaires · événements familiaux · célébrations privées."},{title:"Projets sur mesure",text:"Pour toute demande photo ou vidéo qui mérite une approche particulière."}],finalTitle:"Votre histoire pourrait être la prochaine.",finalText:"Parlez-nous de votre projet et découvrons ensemble comment Divine Motion peut le raconter.",finalCta:"Vérifier notre disponibilité",finalCtaUrl:"/contact"};
type Props={searchParams:Promise<{edit?:string;preview?:string}>};

export default async function Home({searchParams}:Props){
  const query=await searchParams,state=await getEditorState(query.preview==="1"),user=state.user||await getAuthorizedAdmin(),edit=state.edit||(query.edit==="1"&&Boolean(user)),preview=state.preview,publishedStored=await setting("home",homeExtendedDefaults),publishedHome={...homeExtendedDefaults,...publishedStored},general=await setting("general",{}),home=await visualContent("home",{...publishedHome,general},edit||preview),projects=await publishedProjects(),featured=projects.find(project=>project.id===home.featuredProjectId)||projects.find(project=>project.featured),media=user&&(edit||preview)?await editorMedia():[];
  const sectionMap:Record<string,React.ReactNode>={
    manifest:<section className="manifest section wrap" id="manifeste" data-section-key="manifest"><p className="section-index">01 — Notre regard</p><div><h2 data-edit-key="manifestTitle">{home.manifestTitle}</h2><p className="lead" data-edit-key="manifestText">{home.manifestText}</p></div></section>,
    gallery:<section className="editorial-gallery wrap" aria-label="Aperçu du portfolio" data-section-key="gallery" data-gallery-key="gallery">{[0,1,2].map(index=>{const entry=home.gallery?.[index],id=Number(entry&&typeof entry==="object"?entry.id:entry),classes=["gallery-tall","gallery-wide","gallery-small"][index];return id?<img key={`${id}-${index}`} data-media-key={`gallery.${index}.id`} data-alt-key={`gallery.${index}.alt`} className={`cms-image ${classes}`} src={mediaUrl(id,"desktop")} alt={entry?.alt||"Réalisation Divine Motion"}/>:<div key={index} data-media-key={`gallery.${index}.id`} className={classes}><MediaPlaceholder label="Média à sélectionner" ratio={index===0?"portrait":index===1?"landscape":"square"}/></div>})}</section>,
    services:<section className="section services-home wrap" data-section-key="services"><div className="split-heading"><div><p className="section-index">02 — Ce que nous créons</p><h2 data-edit-key="servicesHeading">{home.servicesHeading}</h2></div><p data-edit-key="servicesIntro">{home.servicesIntro}</p></div><div className="service-grid">{home.services.map((item:any,index:number)=><ServiceCard key={index} number={String(index+1).padStart(2,"0")} title={item.title} text={item.text} href={item.href} editBase={`services.${index}`}/>)}</div></section>,
    featured:<section className="featured-story" data-section-key="featured"><div className="featured-media">{featured?.coverMediaId?<img className="cms-image" src={mediaUrl(featured.coverMediaId,"desktop")} alt={featured.peopleNames||featured.title}/>:<MediaPlaceholder label="Histoire à la une" ratio="landscape"/>}</div><div className="featured-copy"><p className="section-index" data-edit-key="featuredLabel">{home.featuredLabel}</p><p className="story-date">{featured?displayDate(featured.projectDate):"08 · 08 · 2026"}</p><h2>{featured?.peopleNames||"David & Emmanuella"}</h2><p data-edit-key="featuredFallbackText">{featured?.excerpt||home.featuredFallbackText}</p><Link className="text-link" href={featured?"/projets/"+featured.slug:"/notre-travail#david-emmanuella"}>Découvrir leur histoire <span>→</span></Link></div></section>,
    film:<section className="film-section section dark-section" data-section-key="film"><div className="wrap film-layout"><div><p className="section-index light">Le mouvement</p><h2 data-edit-key="filmTitle">{home.filmTitle}</h2></div><div className="film-frame" data-media-key="filmMediaId" data-media-types="video,external_video" role="img" aria-label="Film de mariage"><span className="play" aria-hidden="true">▶</span></div><Link className="button button-outline-light" href={home.filmCtaUrl} data-link-label-key="filmCta" data-link-url-key="filmCtaUrl"><span data-edit-key="filmCta">{home.filmCta}</span></Link></div></section>,
    approach:<section className="section approach wrap" data-section-key="approach"><div className="split-heading"><div><p className="section-index">03 — Notre approche</p><h2 data-edit-key="approachTitle">{home.approachTitle}</h2></div><p data-edit-key="approachText">{home.approachText}</p></div><div className="principles">{home.principles.map((principle:any,index:number)=><article key={index}><span>{String(index+1).padStart(2,"0")}</span><h3 data-edit-key={`principles.${index}.title`}>{principle.title}</h3><p data-edit-key={`principles.${index}.text`}>{principle.text}</p></article>)}</div></section>,
    beyond:<section className="beyond section" data-section-key="beyond"><div className="wrap"><div className="split-heading"><div><p className="section-index">04 — Autres histoires</p><h2 data-edit-key="beyondTitle">{home.beyondTitle}</h2></div><p data-edit-key="beyondText">{home.beyondText}</p></div><div className="beyond-grid">{home.beyondItems.map((item:any,index:number)=><article className={index===0?"portrait-ready":""} key={index}><span>{String(index+1).padStart(2,"0")}</span><h3 data-edit-key={`beyondItems.${index}.title`}>{item.title}</h3><p data-edit-key={`beyondItems.${index}.text`}>{item.text}</p></article>)}</div></div></section>,
    final:<section className="final-cta section wrap" data-section-key="final"><p className="eyebrow">La prochaine histoire</p><h2 data-edit-key="finalTitle">{home.finalTitle}</h2><p data-edit-key="finalText">{home.finalText}</p><Link className="button button-dark" href={home.finalCtaUrl} data-link-label-key="finalCta" data-link-url-key="finalCtaUrl"><span data-edit-key="finalCta">{home.finalCta}</span></Link></section>
  };
  for(const item of home.customSections||[])sectionMap[`custom:${item.id}`]=<CustomSection key={item.id} item={item} index={(home.customSections||[]).indexOf(item)}/>;
  const order=[...(home.sectionOrder||defaultOrder),...Object.keys(sectionMap).filter(key=>!(home.sectionOrder||defaultOrder).includes(key))];
  return <><Header general={home.general}/><main className={edit?"visual-editing":""}>
    {home.heroVisible&&<section className="hero" aria-labelledby="hero-title" data-section-key="hero" data-section-locked="true"><div className="hero-media" data-media-key="heroMediaId" data-media-types={home.heroType==="video"?"video,external_video":"image"} aria-hidden="true">{home.heroMediaId?(home.heroType==="video"?<video className="cms-image" autoPlay muted loop playsInline preload="metadata" poster={mediaUrl(home.heroThumbnailMediaId||home.heroFallbackMediaId,"desktop")} style={{objectPosition:home.heroPosition}}><source src={mediaUrl(home.heroMediaId,"original")}/></video>:<picture>{home.heroMobileMediaId&&<source media="(max-width: 720px)" srcSet={mediaUrl(home.heroMobileMediaId,"mobile")}/>}<img className="cms-image" src={mediaUrl(home.heroMediaId,"desktop")} alt="" style={{objectPosition:home.heroPosition}}/></picture>):<div className="hero-placeholder"/>}</div><div className="hero-shade" style={{opacity:Math.max(0,Math.min(100,home.heroOverlay))/100}}/><div className="hero-content wrap"><p className="eyebrow light">Divine Motion · Photographie &amp; Vidéographie</p><h1 id="hero-title" data-edit-key="heroTitle">{home.heroTitle}</h1><p className="hero-copy" data-edit-key="heroSubtitle">{home.heroSubtitle}</p><div className="button-row"><Link className="button button-light" href={home.cta1Url} data-link-label-key="cta1" data-link-url-key="cta1Url"><span data-edit-key="cta1">{home.cta1}</span></Link><Link className="text-link light-link" href={home.cta2Url} data-link-label-key="cta2" data-link-url-key="cta2Url"><span data-edit-key="cta2">{home.cta2}</span> <span>↗</span></Link></div></div><a className="scroll-cue" href="#manifeste"><span/> Découvrir</a></section>}
    {order.map(key=>{const hidden=(home.hiddenSections||[]).includes(key);if(hidden&&!edit)return null;return <div key={key} className={`${hidden?"ve-hidden-section ":""}ve-section-shell ${sectionClass(home,key)}`}>{sectionMap[key]}</div>})}
  </main><Footer general={home.general}/>{user&&(edit||preview)&&<VisualEditor pageKey="home" initial={home} media={media as any[]} preview={preview} editUrl="/" previewUrl="/?preview=1"/>}</>;
}

function CustomSection({item,index}:{item:any;index:number}){const key=`custom:${item.id}`,base=`customSections.${index}`;if(item.type==="separator")return <section className="custom-separator wrap" data-section-key={key}/>;if(item.type==="image-full")return <section className="custom-image-full" data-section-key={key} data-media-key={`${base}.mediaIds.0`}>{item.mediaIds?.[0]?<img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt={item.title||""}/>:<MediaPlaceholder label="Choisir une image" ratio="landscape"/>}</section>;if(item.type==="duo-images")return <section className="custom-duo wrap section" data-section-key={key}><div data-media-key={`${base}.mediaIds.0`}>{item.mediaIds?.[0]?<img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt=""/>:<MediaPlaceholder label="Image 1" ratio="portrait"/>}</div><div data-media-key={`${base}.mediaIds.1`}>{item.mediaIds?.[1]?<img className="cms-image" src={mediaUrl(item.mediaIds[1],"desktop")} alt=""/>:<MediaPlaceholder label="Image 2" ratio="portrait"/>}</div></section>;const dark=item.type==="dark-cinematic"?"dark-section":"";return <section className={`custom-content section ${dark}`} data-section-key={key}><div className="wrap"><p className="section-index">Section Divine Motion</p><h2 data-edit-key={`${base}.title`}>{item.title}</h2><p data-edit-key={`${base}.text`}>{item.text}</p>{item.mediaIds?.[0]&&<div data-media-key={`${base}.mediaIds.0`} className="custom-content-media"><img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt=""/></div>}{item.type==="cta"&&<Link className={dark?"button button-light":"button button-dark"} href={item.ctaUrl||"/contact"} data-link-label-key={`${base}.cta`} data-link-url-key={`${base}.ctaUrl`}><span data-edit-key={`${base}.cta`}>{item.cta||"Découvrir"}</span></Link>}</div></section>}
async function editorMedia(){const result=await db().prepare("SELECT * FROM media WHERE deleted_at IS NULL AND visible=1 ORDER BY updated_at DESC LIMIT 500").all();return result.results||[]}
function sectionClass(home:any,key:string){const value=home.sectionSettings?.[key]||{};return `${value.spacing?`ve-spacing-${value.spacing}`:""} ${value.variant==="dark"?"dark-section":""}`}
