import Link from "next/link";
import type { Metadata } from "next";
import { Footer, Header, MediaPlaceholder, ServiceCard } from "./site-components";
import { displayDate, mediaUrl, pageMetadata, publishedProjects, setting } from "../lib/public-cms";

export async function generateMetadata():Promise<Metadata>{return pageMetadata("home","Divine Motion | Photographie & Vidéographie","Divine Motion raconte vos histoires à travers la photographie et la vidéographie : mariages, portraits, shootings et événements.")}
export const dynamic="force-dynamic";
const defaultOrder=["manifest","gallery","services","featured","film","approach","beyond","final"];
export const homeDefaults={heroType:"image",heroTitle:"Des histoires vraies. Des émotions intactes.",heroSubtitle:"Photographie & vidéographie pour préserver les moments que vous avez vécus — et ceux qui vous ont échappé.",heroMediaId:null as number|null,heroMediaAlt:"",heroMobileMediaId:null as number|null,heroFallbackMediaId:null as number|null,heroThumbnailMediaId:null as number|null,heroOverlay:58,heroPosition:"center center",heroVisible:true,cta1:"Découvrir notre travail",cta1Url:"/notre-travail",cta2:"Vérifier notre disponibilité",cta2Url:"/contact",manifestTitle:"Votre journée passe vite. Vos souvenirs ne devraient pas.",manifestText:"Les regards échangés, les éclats de rire, les gestes discrets et les émotions inattendues font partie de ces moments qui passent parfois en quelques secondes. Divine Motion est là pour les préserver et vous permettre de les revivre.",gallery:[] as number[],featuredProjectId:null as number|null,approachTitle:"Présents quand il le faut. Discrets quand il le faut.",approachText:"Notre approche privilégie les moments naturels. Nous vous guidons lorsque c’est nécessaire, puis nous laissons l’histoire se dérouler afin de capturer les émotions telles qu’elles existent réellement.",principles:[{title:"Observer",text:"Remarquer les détails, les interactions et les moments qui passent parfois inaperçus."},{title:"Raconter",text:"Créer une histoire cohérente plutôt qu’une simple succession d’images."},{title:"Préserver",text:"Transformer des instants en souvenirs capables de traverser les années."}],sectionOrder:defaultOrder,hiddenSections:[] as string[],sectionSettings:{} as Record<string,any>,customSections:[] as Array<Record<string,any>>};
export const homeExtendedDefaults={...homeDefaults,servicesHeading:"Une histoire. Plusieurs façons de la revivre.",servicesIntro:"Le mariage est au cœur de notre univers. La photographie saisit l’instant; le film en conserve le mouvement, la voix et l’atmosphère.",services:[{title:"Photographie",text:"Des images naturelles et élégantes pensées pour raconter une journée dans son ensemble, jusque dans les détails que l’on remarque parfois seulement après.",cta:"Découvrir",href:"/services"},{title:"Vidéographie",text:"Des films qui redonnent vie aux voix, aux mouvements, à l’atmosphère et aux émotions.",cta:"Découvrir",href:"/services"},{title:"Photo + Vidéo",text:"Deux regards complémentaires pour raconter une même histoire de manière cohérente et complète.",cta:"Découvrir",href:"/services"}],featuredLabel:"Histoire à la une",featuredFallbackText:"Une journée remplie d’émotion, de foi, de famille et de célébration.",filmTitle:"Certaines émotions méritent plus qu’une photographie.",filmCta:"Voir le film",filmCtaUrl:"/notre-travail#film",beyondTitle:"Au-delà du mariage",beyondText:"Chaque histoire ne commence pas devant un autel. Divine Motion accompagne également les portraits, shootings créatifs, anniversaires et autres moments que vous souhaitez transformer en souvenirs.",beyondItems:[{title:"Portraits & shootings",text:"Shooting urbain · portrait · lifestyle · couple · projet créatif."},{title:"Anniversaires & événements",text:"Anniversaires · événements familiaux · célébrations privées."},{title:"Projets sur mesure",text:"Pour toute demande photo ou vidéo qui mérite une approche particulière."}],finalTitle:"Votre histoire pourrait être la prochaine.",finalText:"Parlez-nous de votre projet et découvrons ensemble comment Divine Motion peut le raconter.",finalCta:"Vérifier notre disponibilité",finalCtaUrl:"/contact"};

export async function loadHomePublished(){const publishedStored=await setting("home",homeExtendedDefaults),publishedHome={...homeExtendedDefaults,...publishedStored},general=await setting("general",{}),projects=await publishedProjects();return {home:{...publishedHome,general},projects}}

// Rendu partagé entre le site public (app/page.tsx, editable=false) et
// l'éditeur visuel protégé (app/admin/editor/page.tsx, editable=true) : même
// composant, mêmes classes, même DOM — seuls les attributs `data-*` posés
// pour le clic-édition apparaissent quand `editable` est vrai. Une page
// publique normale n'en porte donc aucun.
export function HomeBody({home,projects,editable=false,editBasePath}:{home:Record<string,any>;projects:any[];editable?:boolean;editBasePath?:string}){
  const ea=(attrs:Record<string,string>)=>editable?attrs:{};
  const featured=projects.find(project=>project.id===home.featuredProjectId)||projects.find(project=>project.featured);
  // Un brouillon plus ancien (ou volontairement partiel) peut ne pas contenir
  // `services`/`principles`/`beyondItems` : sans repli, `.map()` sur
  // `undefined` faisait planter toute la route (voir l'audit Phase UX 2 bis,
  // point 2 — même classe de bug que sur /admin/editor/services et /a-propos).
  const services=Array.isArray(home.services)?home.services:[],principles=Array.isArray(home.principles)?home.principles:[],beyondItems=Array.isArray(home.beyondItems)?home.beyondItems:[];
  const sectionMap:Record<string,React.ReactNode>={
    manifest:<section className="manifest section wrap" id="manifeste" {...ea({"data-section-key":"manifest"})}><p className="section-index">01 — Notre regard</p><div><h2 {...ea({"data-edit-key":"manifestTitle"})}>{home.manifestTitle}</h2><p className="lead" {...ea({"data-edit-key":"manifestText"})}>{home.manifestText}</p></div></section>,
    gallery:<section className="editorial-gallery wrap" aria-label="Aperçu du portfolio" {...ea({"data-section-key":"gallery","data-gallery-key":"gallery"})}>{[0,1,2].map(index=>{const entry=home.gallery?.[index],id=Number(entry&&typeof entry==="object"?entry.id:entry),classes=["gallery-tall","gallery-wide","gallery-small"][index];return id?<img key={`${id}-${index}`} {...ea({"data-media-key":`gallery.${index}.id`,"data-alt-key":`gallery.${index}.alt`})} className={`cms-image ${classes}`} src={mediaUrl(id,"desktop")} alt={entry?.alt||"Réalisation Divine Motion"}/>:<div key={index} {...ea({"data-media-key":`gallery.${index}.id`})} className={classes}><MediaPlaceholder label="Média à sélectionner" ratio={index===0?"portrait":index===1?"landscape":"square"}/></div>})}</section>,
    services:<section className="section services-home wrap" {...ea({"data-section-key":"services"})}><div className="split-heading"><div><p className="section-index">02 — Ce que nous créons</p><h2 {...ea({"data-edit-key":"servicesHeading"})}>{home.servicesHeading}</h2></div><p {...ea({"data-edit-key":"servicesIntro"})}>{home.servicesIntro}</p></div><div className="service-grid">{services.map((item:any,index:number)=><ServiceCard key={index} number={String(index+1).padStart(2,"0")} title={item.title} text={item.text} href={item.href} editBase={editable?`services.${index}`:undefined}/>)}</div></section>,
    featured:<section className="featured-story" {...ea({"data-section-key":"featured"})}><div className="featured-media">{featured?.coverMediaId?<img className="cms-image" src={mediaUrl(featured.coverMediaId,"desktop")} alt={featured.peopleNames||featured.title}/>:<MediaPlaceholder label="Histoire à la une" ratio="landscape"/>}</div><div className="featured-copy"><p className="section-index" {...ea({"data-edit-key":"featuredLabel"})}>{home.featuredLabel}</p><p className="story-date">{featured?displayDate(featured.projectDate):"08 · 08 · 2026"}</p><h2>{featured?.peopleNames||"David & Emmanuella"}</h2><p {...ea({"data-edit-key":"featuredFallbackText"})}>{featured?.excerpt||home.featuredFallbackText}</p><Link className="text-link" href={featured?"/projets/"+featured.slug:"/notre-travail#david-emmanuella"}>Découvrir leur histoire <span>→</span></Link></div></section>,
    film:<section className="film-section section dark-section" {...ea({"data-section-key":"film"})}><div className="wrap film-layout"><div><p className="section-index light">Le mouvement</p><h2 {...ea({"data-edit-key":"filmTitle"})}>{home.filmTitle}</h2></div><div className="film-frame" {...ea({"data-media-key":"filmMediaId","data-media-types":"video,external_video"})} role="img" aria-label="Film de mariage"><span className="play" aria-hidden="true">▶</span></div><Link className="button button-outline-light" href={home.filmCtaUrl||"/contact"} {...ea({"data-link-label-key":"filmCta","data-link-url-key":"filmCtaUrl"})}><span {...ea({"data-edit-key":"filmCta"})}>{home.filmCta}</span></Link></div></section>,
    approach:<section className="section approach wrap" {...ea({"data-section-key":"approach"})}><div className="split-heading"><div><p className="section-index">03 — Notre approche</p><h2 {...ea({"data-edit-key":"approachTitle"})}>{home.approachTitle}</h2></div><p {...ea({"data-edit-key":"approachText"})}>{home.approachText}</p></div><div className="principles">{principles.map((principle:any,index:number)=><article key={index}><span>{String(index+1).padStart(2,"0")}</span><h3 {...ea({"data-edit-key":`principles.${index}.title`})}>{principle.title}</h3><p {...ea({"data-edit-key":`principles.${index}.text`})}>{principle.text}</p></article>)}</div></section>,
    beyond:<section className="beyond section" {...ea({"data-section-key":"beyond"})}><div className="wrap"><div className="split-heading"><div><p className="section-index">04 — Autres histoires</p><h2 {...ea({"data-edit-key":"beyondTitle"})}>{home.beyondTitle}</h2></div><p {...ea({"data-edit-key":"beyondText"})}>{home.beyondText}</p></div><div className="beyond-grid">{beyondItems.map((item:any,index:number)=><article className={index===0?"portrait-ready":""} key={index}><span>{String(index+1).padStart(2,"0")}</span><h3 {...ea({"data-edit-key":`beyondItems.${index}.title`})}>{item.title}</h3><p {...ea({"data-edit-key":`beyondItems.${index}.text`})}>{item.text}</p></article>)}</div></div></section>,
    final:<section className="final-cta section wrap" {...ea({"data-section-key":"final"})}><p className="eyebrow">La prochaine histoire</p><h2 {...ea({"data-edit-key":"finalTitle"})}>{home.finalTitle}</h2><p {...ea({"data-edit-key":"finalText"})}>{home.finalText}</p><Link className="button button-dark" href={home.finalCtaUrl||"/contact"} {...ea({"data-link-label-key":"finalCta","data-link-url-key":"finalCtaUrl"})}><span {...ea({"data-edit-key":"finalCta"})}>{home.finalCta}</span></Link></section>
  };
  for(const item of home.customSections||[])sectionMap[`custom:${item.id}`]=<CustomSection key={item.id} item={item} index={(home.customSections||[]).indexOf(item)} editable={editable}/>;
  const order=[...(home.sectionOrder||defaultOrder),...Object.keys(sectionMap).filter(key=>!(home.sectionOrder||defaultOrder).includes(key))];
  return <><Header general={home.general} editable={editable} editBasePath={editBasePath}/><main className={editable?"visual-editing":""}>
    {home.heroVisible&&<section className="hero" aria-labelledby="hero-title" {...ea({"data-section-key":"hero","data-section-locked":"true"})}><div className="hero-media" {...ea({"data-media-key":"heroMediaId","data-media-types":home.heroType==="video"?"video,external_video":"image","data-position-key":"heroPosition",...(home.heroType==="video"?{}:{"data-alt-key":"heroMediaAlt"})})} aria-hidden="true">{home.heroMediaId?(home.heroType==="video"?<video className="cms-image" autoPlay muted loop playsInline preload="metadata" poster={mediaUrl(home.heroThumbnailMediaId||home.heroFallbackMediaId,"desktop")} style={{objectPosition:home.heroPosition}}><source src={mediaUrl(home.heroMediaId,"original")}/></video>:<picture>{home.heroMobileMediaId&&<source media="(max-width: 720px)" srcSet={mediaUrl(home.heroMobileMediaId,"mobile")}/>}<img className="cms-image" src={mediaUrl(home.heroMediaId,"desktop")} alt={home.heroMediaAlt||""} style={{objectPosition:home.heroPosition}}/></picture>):<div className="hero-placeholder"/>}</div><div className="hero-shade" style={{opacity:Math.max(0,Math.min(100,home.heroOverlay))/100}}/><div className="hero-content wrap"><p className="eyebrow light">Divine Motion · Photographie &amp; Vidéographie</p><h1 id="hero-title" {...ea({"data-edit-key":"heroTitle"})}>{home.heroTitle}</h1><p className="hero-copy" {...ea({"data-edit-key":"heroSubtitle"})}>{home.heroSubtitle}</p><div className="button-row"><Link className="button button-light" href={home.cta1Url||"/contact"} {...ea({"data-link-label-key":"cta1","data-link-url-key":"cta1Url"})}><span {...ea({"data-edit-key":"cta1"})}>{home.cta1}</span></Link><Link className="text-link light-link" href={home.cta2Url||"/contact"} {...ea({"data-link-label-key":"cta2","data-link-url-key":"cta2Url"})}><span {...ea({"data-edit-key":"cta2"})}>{home.cta2}</span> <span>↗</span></Link></div></div><a className="scroll-cue" href="#manifeste"><span/> Découvrir</a></section>}
    {order.map(key=>{const hidden=(home.hiddenSections||[]).includes(key);if(hidden&&!editable)return null;return <div key={key} className={`${hidden?"ve-hidden-section ":""}ve-section-shell ${sectionClass(home,key)}`}>{sectionMap[key]}</div>})}
  </main><Footer general={home.general} editable={editable} editBasePath={editBasePath}/></>;
}

export default async function Home(){
  const {home,projects}=await loadHomePublished();
  return <HomeBody home={home} projects={projects}/>;
}

function CustomSection({item,index,editable}:{item:any;index:number;editable:boolean}){const key=`custom:${item.id}`,base=`customSections.${index}`,ea=(attrs:Record<string,string>)=>editable?attrs:{};if(item.type==="separator")return <section className="custom-separator wrap" {...ea({"data-section-key":key})}/>;if(item.type==="image-full")return <section className="custom-image-full" {...ea({"data-section-key":key,"data-media-key":`${base}.mediaIds.0`})}>{item.mediaIds?.[0]?<img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt={item.title||""}/>:<MediaPlaceholder label="Choisir une image" ratio="landscape"/>}</section>;if(item.type==="duo-images")return <section className="custom-duo wrap section" {...ea({"data-section-key":key})}><div {...ea({"data-media-key":`${base}.mediaIds.0`})}>{item.mediaIds?.[0]?<img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt=""/>:<MediaPlaceholder label="Image 1" ratio="portrait"/>}</div><div {...ea({"data-media-key":`${base}.mediaIds.1`})}>{item.mediaIds?.[1]?<img className="cms-image" src={mediaUrl(item.mediaIds[1],"desktop")} alt=""/>:<MediaPlaceholder label="Image 2" ratio="portrait"/>}</div></section>;const dark=item.type==="dark-cinematic"?"dark-section":"";return <section className={`custom-content section ${dark}`} {...ea({"data-section-key":key})}><div className="wrap"><p className="section-index">Section Divine Motion</p><h2 {...ea({"data-edit-key":`${base}.title`})}>{item.title}</h2><p {...ea({"data-edit-key":`${base}.text`})}>{item.text}</p>{item.mediaIds?.[0]&&<div {...ea({"data-media-key":`${base}.mediaIds.0`})} className="custom-content-media"><img className="cms-image" src={mediaUrl(item.mediaIds[0],"desktop")} alt=""/></div>}{item.type==="cta"&&<Link className={dark?"button button-light":"button button-dark"} href={item.ctaUrl||"/contact"} {...ea({"data-link-label-key":`${base}.cta`,"data-link-url-key":`${base}.ctaUrl`})}><span {...ea({"data-edit-key":`${base}.cta`})}>{item.cta||"Découvrir"}</span></Link>}</div></section>}
function sectionClass(home:any,key:string){const value=home.sectionSettings?.[key]||{};return `${value.spacing?`ve-spacing-${value.spacing}`:""} ${value.variant==="dark"?"dark-section":""}`}
