"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
const nav=[["Notre travail","/notre-travail"],["Services","/services"],["À propos","/a-propos"],["Contact","/contact"]];
function useGeneral(){const [general,setGeneral]=useState<Record<string,any>>({});useEffect(()=>{fetch("/api/content/settings").then(response=>response.json()).then(value=>setGeneral(value.general||{})).catch(()=>{})},[]);return general}
// `editable`/`editBasePath` n'existent que pour le rendu dans l'éditeur visuel
// protégé (voir app/admin/editor/**) : par défaut (site public), ni l'un ni
// l'autre n'est fourni, donc ce composant se comporte exactement comme avant.
// `editBasePath` fait pointer la navigation vers l'équivalent éditeur d'une
// page plutôt que vers la page publique, pour ne jamais quitter le mode
// édition en cliquant sur un lien du header/footer.
type ShellProps={general?:Record<string,any>;editable?:boolean;editBasePath?:string};
function navHref(href:string,editBasePath?:string){if(!editBasePath)return href;return href==="/"?editBasePath:`${editBasePath}${href}`}
export function Header({general:provided,editBasePath}:ShellProps={}){const [open,setOpen]=useState(false),pathname=usePathname(),loaded=useGeneral(),general=provided||loaded,logo=general.logoMainId?`/api/media/${general.logoMainId}?variant=desktop`:"/assets/divine-motion-header.png";return <header className="site-header"><Link className="brand" href={navHref("/",editBasePath)} aria-label="Divine Motion — Accueil"><img src={logo} alt="Divine Motion — Photographie & Vidéographie"/></Link><nav className={open?"main-nav open":"main-nav"} aria-label="Navigation principale">{nav.map(([label,href])=><Link className={pathname===href?"active":""} href={navHref(href,editBasePath)} onClick={()=>setOpen(false)} key={href}>{label}</Link>)}<Link className="nav-book" href={navHref("/contact",editBasePath)} onClick={()=>setOpen(false)}>Réserver</Link></nav><button className={open?"menu-toggle open":"menu-toggle"} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Fermer le menu":"Ouvrir le menu"}><span/><span/></button></header>}
export function Footer({general:provided,editable=false,editBasePath}:ShellProps={}){const loaded=useGeneral(),general=provided||loaded,logo=general.logoOrangeId?`/api/media/${general.logoOrangeId}?variant=desktop`:"/assets/divine-motion-orange.gif",ea=(a:Record<string,string>)=>editable?a:{};return <footer className="site-footer" {...ea({"data-section-key":"footer"})}><div className="wrap footer-grid"><div className="footer-brand"><div {...ea({"data-media-key":"general.logoOrangeId"})}><img src={logo} alt="Divine Motion — Photographie & Vidéographie"/></div><p><span {...ea({"data-edit-key":"general.cities"})}>{general.cities||"Québec · Ottawa"}</span><br/>{general.travel!==false&&<span {...ea({"data-edit-key":"general.travelText"})}>{general.travelText||"Disponible pour voyager"}</span>}</p></div><div><p className="footer-label">Explorer</p>{nav.map(([label,href])=><Link href={navHref(href,editBasePath)} key={href}>{label}</Link>)}</div><div><p className="footer-label">Réseaux</p>{general.instagram?<a href={general.instagram} target="_blank">Instagram</a>:<span>Instagram</span>}{general.facebook?<a href={general.facebook} target="_blank">Facebook</a>:<span>Facebook</span>}{general.tiktok?<a href={general.tiktok} target="_blank">TikTok</a>:<span>TikTok</span>}</div><div className="footer-note"><p {...ea({"data-edit-key":"general.footerText"})}>{general.footerText||"Des histoires vraies. Des émotions intactes."}</p></div></div><div className="wrap footer-bottom"><span {...ea({"data-edit-key":"general.copyright"})}>{general.copyright||`© ${new Date().getFullYear()} Divine Motion — Tous droits réservés`}</span><Link href={navHref("/contact",editBasePath)}>Parler de votre projet ↗</Link></div></footer>}
export function MediaPlaceholder({label,ratio="landscape",className=""}:{label:string;ratio?:string;className?:string}){return <div className={`media-placeholder ${ratio} ${className}`} role="img" aria-label={label}/>}
export function ServiceCard({number,title,text,cta="Découvrir",href="/services",editBase}:{number:string;title:string;text:string;cta?:string;href?:string;editBase?:string}){return <article className="service-card"><span>{number}</span><h3 {...(editBase?{"data-edit-key":`${editBase}.title`}:{})}>{title}</h3><p {...(editBase?{"data-edit-key":`${editBase}.text`}:{})}>{text}</p><Link className="text-link" href={href} {...(editBase?{"data-link-label-key":`${editBase}.cta`,"data-link-url-key":`${editBase}.href`}:{})}><span {...(editBase?{"data-edit-key":`${editBase}.cta`}:{})}>{cta}</span> <b>↗</b></Link></article>}
export function PageShell({children,general,editable=false,editBasePath}:ShellProps&{children:React.ReactNode}){return <><Header general={general} editable={editable} editBasePath={editBasePath}/><main>{children}</main><Footer general={general} editable={editable} editBasePath={editBasePath}/></>}
