"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
const nav=[["Notre travail","/notre-travail"],["Services","/services"],["À propos","/a-propos"],["Contact","/contact"]];
function useGeneral(){const [general,setGeneral]=useState<Record<string,any>>({});useEffect(()=>{fetch("/api/content/settings").then(response=>response.json()).then(value=>setGeneral(value.general||{})).catch(()=>{})},[]);return general}
export function Header({general:provided}:{general?:Record<string,any>}={}){const [open,setOpen]=useState(false),pathname=usePathname(),loaded=useGeneral(),general=provided||loaded,logo=general.logoMainId?`/api/media/${general.logoMainId}?variant=desktop`:"/assets/divine-motion-header.png";return <header className="site-header"><Link className="brand" href="/" aria-label="Divine Motion — Accueil"><img src={logo} alt="Divine Motion — Photographie & Vidéographie"/></Link><nav className={open?"main-nav open":"main-nav"} aria-label="Navigation principale">{nav.map(([label,href])=><Link className={pathname===href?"active":""} href={href} onClick={()=>setOpen(false)} key={href}>{label}</Link>)}<Link className="nav-book" href="/contact" onClick={()=>setOpen(false)}>Réserver</Link></nav><button className={open?"menu-toggle open":"menu-toggle"} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Fermer le menu":"Ouvrir le menu"}><span/><span/></button></header>}
export function Footer({general:provided}:{general?:Record<string,any>}={}){const loaded=useGeneral(),general=provided||loaded,logo=general.logoOrangeId?`/api/media/${general.logoOrangeId}?variant=desktop`:"/assets/divine-motion-orange.gif";return <footer className="site-footer" data-section-key="footer"><div className="wrap footer-grid"><div className="footer-brand"><div data-media-key="general.logoOrangeId"><img src={logo} alt="Divine Motion — Photographie & Vidéographie"/></div><p><span data-edit-key="general.cities">{general.cities||"Québec · Ottawa"}</span><br/>{general.travel!==false&&<span data-edit-key="general.travelText">{general.travelText||"Disponible pour voyager"}</span>}</p></div><div><p className="footer-label">Explorer</p>{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</div><div><p className="footer-label">Réseaux</p>{general.instagram?<a href={general.instagram} target="_blank">Instagram</a>:<span>Instagram</span>}{general.facebook?<a href={general.facebook} target="_blank">Facebook</a>:<span>Facebook</span>}{general.tiktok?<a href={general.tiktok} target="_blank">TikTok</a>:<span>TikTok</span>}</div><div className="footer-note"><p data-edit-key="general.footerText">{general.footerText||"Des histoires vraies. Des émotions intactes."}</p></div></div><div className="wrap footer-bottom"><span data-edit-key="general.copyright">{general.copyright||`© ${new Date().getFullYear()} Divine Motion — Tous droits réservés`}</span><Link href="/contact">Parler de votre projet ↗</Link></div></footer>}
export function MediaPlaceholder({label,ratio="landscape",className=""}:{label:string;ratio?:string;className?:string}){return <div className={`media-placeholder ${ratio} ${className}`} role="img" aria-label={label}/>}
export function ServiceCard({number,title,text,cta="Découvrir",href="/services",editBase}:{number:string;title:string;text:string;cta?:string;href?:string;editBase?:string}){return <article className="service-card"><span>{number}</span><h3 {...(editBase?{"data-edit-key":`${editBase}.title`}:{})}>{title}</h3><p {...(editBase?{"data-edit-key":`${editBase}.text`}:{})}>{text}</p><Link className="text-link" href={href} {...(editBase?{"data-link-label-key":`${editBase}.cta`,"data-link-url-key":`${editBase}.href`}:{})}><span {...(editBase?{"data-edit-key":`${editBase}.cta`}:{})}>{cta}</span> <b>↗</b></Link></article>}
export function PageShell({children,general}:{children:React.ReactNode;general?:Record<string,any>}){return <><Header general={general}/><main>{children}</main><Footer general={general}/></>}
