"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { MediaItem, MediaPicker } from "./admin/media-picker";
import { normalizeMediaList } from "../lib/media-normalize";
import { mediaLabel, heroMediaTarget } from "../lib/media-label";
import { sectionOrder, sectionBounds, sectionLabel } from "../lib/section-order";
type Props={pageKey:string;initial:Record<string,any>;media:MediaItem[];preview?:boolean;editUrl:string;previewUrl:string;pageLabel?:string;hasDraft?:boolean};
type MediaTarget={key:string;types:string[];altKey?:string;replaceIndex?:number}|null;
// Liste volontairement restreinte aux types de sections réellement implémentés
// par CustomSection (app/page.tsx) — proposer "Vidéo", "Services" ou "Galerie
// mosaïque" y rendrait en réalité un bloc texte générique, ce qui trahirait le
// choix affiché ici (voir l'audit Phase UX 2, section 4).
const sectionTypes=[["title-text","Texte éditorial"],["image-full","Image plein écran"],["duo-images","Duo d’images"],["cta","Appel à l’action"],["dark-cinematic","Section sombre"]];
// Sélecteur de page toujours restreint à /admin/editor/* (voir Header pour
// le même principe côté rendu public) — la page projet en cours est ajoutée
// dynamiquement si elle n'y figure pas déjà.
const pageNav=[["/admin/editor","Accueil"],["/admin/editor/notre-travail","Notre travail"],["/admin/editor/services","Services"],["/admin/editor/a-propos","À propos"],["/admin/editor/contact","Contact"]];
export function VisualEditor({pageKey,initial,media,preview=false,editUrl,previewUrl,pageLabel,hasDraft=false}:Props){
 const [content,setContent]=useState(initial),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(hasDraft?"Brouillon enregistré":"Publié"),[lastSavedAt,setLastSavedAt]=useState<Date|null>(null),[picker,setPicker]=useState<MediaTarget>(null),[mediaMenu,setMediaMenu]=useState<MediaTarget>(null),[galleryKey,setGalleryKey]=useState<string|null>(null),[selectedSection,setSelectedSection]=useState<string|null>(null),[adding,setAdding]=useState<{after:string|null}|null>(null),[linkKeys,setLinkKeys]=useState<{label:string;url:string}|null>(null),[collapsed,setCollapsed]=useState(false),[activeText,setActiveText]=useState<{node:HTMLElement;path:string;before:string}|null>(null),[moreOpen,setMoreOpen]=useState(false);const history=useRef<Record<string,any>[]>([initial]),cursor=useRef(0),drag=useRef<number|null>(null),contentRef=useRef(content);contentRef.current=content;const selectedLink=useMemo(()=>linkKeys?{label:String(get(content,linkKeys.label)||""),url:String(get(content,linkKeys.url)||"")}:null,[content,linkKeys]),gallery=galleryKey?normalizeMediaList(get(content,galleryKey),{includeHidden:true}):[];
 const mediaAsideRef=useRef<HTMLElement>(null),sectionSheetRef=useRef<HTMLElement>(null),galleryPanelRef=useRef<HTMLElement>(null);
 // Focus posé sur le panneau à son ouverture — sans quoi le clavier reste sur
 // l'élément cliqué dans la page derrière, invisible sous le panneau.
 useEffect(()=>{if(mediaMenu)mediaAsideRef.current?.focus()},[mediaMenu]);
 useEffect(()=>{if(selectedSection)sectionSheetRef.current?.focus()},[selectedSection]);
 useEffect(()=>{if(galleryKey)galleryPanelRef.current?.focus()},[galleryKey]);
 function commit(next:Record<string,any>,record=true){setContent(next);contentRef.current=next;setDirty(true);setMessage("Modifications non publiées");if(record){history.current=history.current.slice(0,cursor.current+1);history.current.push(structuredClone(next));cursor.current=history.current.length-1}}
 function change(path:string,value:any,record=true){commit(set(contentRef.current,path,value),record)}
 function undo(){if(cursor.current<1)return;cursor.current--;const next=structuredClone(history.current[cursor.current]);setContent(next);contentRef.current=next;applyDom(next);setDirty(true)}function redo(){if(cursor.current>=history.current.length-1)return;cursor.current++;const next=structuredClone(history.current[cursor.current]);setContent(next);contentRef.current=next;applyDom(next);setDirty(true)}
 async function request(kind:"save"|"publish"|"discard"|"restore",body=contentRef.current){setSaving(true);try{const response=await fetch("/api/admin/visual-editor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pageKey,action:kind,content:body})}),json=await response.json();if(!response.ok)throw new Error(json.error||"Opération impossible");if(json.content){setContent(json.content);contentRef.current=json.content;applyDom(json.content)}setDirty(false);if(kind==="save"||kind==="publish")setLastSavedAt(new Date());setMessage(kind==="publish"?"Publié":kind==="save"?"Brouillon enregistré":kind==="restore"?"Version restaurée":"Brouillon annulé");return true}catch(error){setMessage(error instanceof Error?error.message:"Erreur serveur");return false}finally{setSaving(false)}}
 async function publish(){if(confirm("Publier cette version ?"))await request("publish")}async function discard(){setMoreOpen(false);if(confirm("Abandonner le brouillon et revenir à la dernière version publiée ? Cette action est irréversible.")&&await request("discard"))location.reload()}async function openPreview(){if(dirty&&!await request("save"))return;location.href=previewUrl}
 function validateText(){if(!activeText)return;activeText.node.removeAttribute("contenteditable");commit(contentRef.current);setActiveText(null)}function cancelText(){if(!activeText)return;activeText.node.innerText=activeText.before;activeText.node.removeAttribute("contenteditable");change(activeText.path,activeText.before);setActiveText(null)}
 useEffect(()=>{document.body.classList.add("ve-active");return()=>document.body.classList.remove("ve-active")},[]);
 useEffect(()=>{if(preview)return;const click=(event:MouseEvent)=>{const target=event.target as HTMLElement;
  // Un clic en dehors du champ en cours d'édition le valide d'abord (au lieu
  // de le laisser bloqué en édition) — le clic continue ensuite son
  // traitement normal, sauf s'il visait la barre/panneaux de l'éditeur.
  if(activeText&&!activeText.node.contains(target)&&!target.closest(".ve-ui"))validateText();
  if(moreOpen&&!target.closest(".ve-more"))setMoreOpen(false);
  if(target.closest(".ve-ui"))return;const link=target.closest<HTMLElement>("[data-link-label-key]");if(link){event.preventDefault();setLinkKeys({label:link.dataset.linkLabelKey!,url:link.dataset.linkUrlKey!});return}const mediaTarget=target.closest<HTMLElement>("[data-media-key]");if(mediaTarget){event.preventDefault();event.stopPropagation();setMediaMenu({key:mediaTarget.dataset.mediaKey!,types:(mediaTarget.dataset.mediaTypes||"image").split(","),altKey:mediaTarget.dataset.altKey});return}const editable=target.closest<HTMLElement>("[data-edit-key]");if(editable){event.preventDefault();event.stopPropagation();if(activeText?.node===editable)return;activeText?.node.removeAttribute("contenteditable");editable.contentEditable="true";editable.focus();setActiveText({node:editable,path:editable.dataset.editKey!,before:editable.innerText});return}const galleryTarget=target.closest<HTMLElement>("[data-gallery-key]");if(galleryTarget){event.preventDefault();setGalleryKey(galleryTarget.dataset.galleryKey!);return}const section=target.closest<HTMLElement>("[data-section-key]");if(section){event.preventDefault();setSelectedSection(section.dataset.sectionKey!);setCollapsed(false)}};const input=(event:Event)=>{const element=(event.target as HTMLElement).closest<HTMLElement>("[data-edit-key]");if(element){const next=set(contentRef.current,element.dataset.editKey!,element.innerText.trimStart());setContent(next);contentRef.current=next;setDirty(true);setMessage("Modifications non publiées")}};
  // Échap annule la modification en cours ; Entrée la valide — sauf dans un
  // paragraphe, où Entrée doit rester un retour à la ligne normal.
  const keydown=(event:KeyboardEvent)=>{if(!activeText)return;if(event.key==="Escape"){event.preventDefault();cancelText();return}if(event.key==="Enter"&&!event.shiftKey&&activeText.node.tagName!=="P"){event.preventDefault();validateText()}};
  const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};document.addEventListener("click",click,true);document.addEventListener("input",input,true);document.addEventListener("keydown",keydown,true);window.addEventListener("beforeunload",before);return()=>{document.removeEventListener("click",click,true);document.removeEventListener("input",input,true);document.removeEventListener("keydown",keydown,true);window.removeEventListener("beforeunload",before)}},[dirty,preview,activeText,moreOpen]);
 // Met en évidence, directement dans le rendu public partagé, la section
 // actuellement ouverte dans le panneau latéral — sans quoi rien ne montrait
 // quelle section précise était sélectionnée une fois le panneau ouvert.
 useEffect(()=>{if(!selectedSection)return;const node=document.querySelector<HTMLElement>(`[data-section-key="${selectedSection}"]`);node?.classList.add("ve-section-active");return()=>node?.classList.remove("ve-section-active")},[selectedSection]);
 // Même principe pour le média actuellement ouvert dans le panneau contextuel
 // — sans quoi rien ne montrait, dans le rendu, quel média précis était visé.
 useEffect(()=>{if(!mediaMenu)return;const node=document.querySelector<HTMLElement>(`[data-media-key="${mediaMenu.key}"]`);node?.classList.add("ve-media-active");return()=>node?.classList.remove("ve-media-active")},[mediaMenu]);
 useEffect(()=>{if(!dirty||preview||activeText)return;const timer=setTimeout(()=>request("save"),1400);return()=>clearTimeout(timer)},[content,dirty,preview,activeText]);
 if(preview)return <a className="ve-preview-return ve-ui" href={editUrl}>← Retour à l’éditeur</a>;
 async function chooseMedia(ids:number[]){if(!picker)return;const next=set(contentRef.current,picker.key,ids[0]);commit(next);setPicker(null);setMediaMenu(null);if(await request("save",next))location.reload()}async function removeMedia(){if(!mediaMenu)return;const next=set(contentRef.current,mediaMenu.key,null);commit(next);setMediaMenu(null);if(await request("save",next))location.reload()}
 async function moveSection(direction:number){if(!selectedSection)return;if(selectedSection.startsWith("chapter:")){const index=Number(selectedSection.split(":")[1]),target=index+direction,sections=[...(content.sections||[])];if(index<0||target<0||target>=sections.length)return;[sections[index],sections[target]]=[sections[target],sections[index]];const next={...content,sections};commit(next);if(await request("save",next))location.reload();return}if(selectedSection.startsWith("service:")||selectedSection.startsWith("team:")){const collection=selectedSection.startsWith("service:")?"services":"team",index=Number(selectedSection.split(":")[1]),target=index+direction,items=[...(content[collection]||[])];if(index<0||target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];items.forEach((item:any,i:number)=>item.displayOrder=i);const next={...content,[collection]:items};commit(next);if(await request("save",next))location.reload();return}const order=sectionOrder(content),index=order.indexOf(selectedSection),target=index+direction;if(index<0||target<0||target>=order.length)return;[order[index],order[target]]=[order[target],order[index]];const next=set(contentRef.current,"sectionOrder",order);commit(next);if(await request("save",next))location.reload()}
 function toggleSection(){if(!selectedSection)return;if(selectedSection.startsWith("chapter:")){const index=Number(selectedSection.split(":")[1]),sections=[...(content.sections||[])];sections[index]={...sections[index],enabled:sections[index]?.enabled===false};commit({...content,sections});return}if(selectedSection.startsWith("service:")||selectedSection.startsWith("team:")){const collection=selectedSection.startsWith("service:")?"services":"team",index=Number(selectedSection.split(":")[1]),items=[...(content[collection]||[])];items[index]={...items[index],visible:items[index]?.visible===false};commit({...content,[collection]:items});return}const hidden=new Set<string>(content.hiddenSections||[]);hidden.has(selectedSection)?hidden.delete(selectedSection):hidden.add(selectedSection);change("hiddenSections",[...hidden])}
 async function addSection(type:string){const item={id:crypto.randomUUID(),type,title:sectionTypes.find(entry=>entry[0]===type)?.[1]||"Nouvelle section",text:"Cliquez pour modifier ce texte.",mediaIds:[],cta:"Découvrir",ctaUrl:"/contact",visible:true},key=`custom:${item.id}`,order=sectionOrder(content),after=adding?.after,index=after?order.indexOf(after)+1:order.length;order.splice(Math.max(0,index),0,key);const next={...content,customSections:[...(content.customSections||[]),item],sectionOrder:order};commit(next);setAdding(null);await request("save",next);location.reload()}
 function setGallery(next:any[]){if(galleryKey)change(galleryKey,next)}function addGallery(ids:number[]){const current=normalizeMediaList(get(contentRef.current,galleryKey!),{includeHidden:true}),existing=new Set(current.map(x=>x.id));setGallery([...current,...ids.filter(id=>!existing.has(id)).map(id=>({id,alt:"",caption:"",hidden:false}))]);setPicker(null)}
 function replaceGalleryItem(ids:number[]){if(!galleryKey||picker?.replaceIndex===undefined)return;const current=normalizeMediaList(get(contentRef.current,galleryKey),{includeHidden:true}),next=[...current],index=picker!.replaceIndex!;next[index]={...next[index],id:ids[0]};setGallery(next);setPicker(null)}
 const currentInNav=pageNav.some(([href])=>href===editUrl);
 const mediaHasValue=mediaMenu?Boolean(get(content,mediaMenu.key)):false;
 return <><div className="ve-bar ve-ui"><div><b>Divine Motion — {pageLabel||"Mode édition"}</b><small className={dirty?"dirty":""}>{saving?"Enregistrement…":message}{lastSavedAt&&!saving&&<i className="ve-saved-at">{lastSavedAt.toLocaleTimeString("fr-CA",{hour:"2-digit",minute:"2-digit"})}</i>}</small></div><select className="ve-page-select" value={editUrl} onChange={e=>{location.href=e.target.value}} aria-label="Changer de page">{!currentInNav&&<option value={editUrl}>{pageLabel||"Cette page"}</option>}{pageNav.map(([href,label])=><option key={href} value={href}>{label}</option>)}</select><div className="ve-history"><button onClick={undo} disabled={cursor.current<1} title="Annuler la dernière modification (local)">↶</button><button onClick={redo} disabled={cursor.current>=history.current.length-1} title="Rétablir la modification annulée">↷</button></div><nav><button onClick={openPreview}>Prévisualiser</button><button className="ve-publish" onClick={publish} disabled={saving}>Publier</button><div className="ve-more"><button className="ve-more-trigger" onClick={()=>setMoreOpen(!moreOpen)} aria-label="Plus d’actions" aria-expanded={moreOpen}>⋯</button>{moreOpen&&<div className="ve-more-menu"><button className="ve-danger" onClick={discard}>Abandonner le brouillon</button></div>}</div><a href="/admin">Quitter</a></nav></div>
 {activeText&&<div className="ve-inline-actions ve-ui"><button onClick={validateText}>✓ Valider</button><button onClick={cancelText}>✕ Annuler</button></div>}
 {mediaMenu&&<aside ref={mediaAsideRef} tabIndex={-1} className="ve-context ve-ui"><b>{mediaLabel(mediaMenu.key,mediaMenu.types)}</b><div className="ve-block"><p className="ve-block-title">Média</p>{mediaHasValue?<><button onClick={()=>setPicker(mediaMenu)}>🖼 Remplacer depuis la médiathèque</button><a href="/admin" target="_blank">↑ Téléverser un nouveau média</a>{mediaMenu.altKey&&<label>Alt<input value={get(content,mediaMenu.altKey)||""} onChange={e=>change(mediaMenu.altKey!,e.target.value)}/></label>}<button onClick={removeMedia}>Retirer</button></>:<><button onClick={()=>setPicker(mediaMenu)}>🖼 Ajouter depuis la médiathèque</button><a href="/admin" target="_blank">↑ Téléverser un nouveau média</a></>}</div>{mediaMenu.key==="heroMediaId"&&mediaHasValue&&<div className="ve-block"><p className="ve-block-title">Apparence</p><label>Overlay<input type="range" min="0" max="90" step="5" value={content.heroOverlay??58} onChange={e=>change("heroOverlay",Number(e.target.value))}/></label><label>Cadrage<select value={content.heroPosition||"center center"} onChange={e=>{change("heroPosition",e.target.value);applyPosition("heroPosition",e.target.value)}}><option value="center center">Centre</option><option value="center top">Haut</option><option value="center bottom">Bas</option></select></label></div>}<button className="ve-close" aria-label="Fermer le panneau média" onClick={()=>setMediaMenu(null)}>×</button></aside>}
 {selectedSection&&<aside ref={sectionSheetRef} tabIndex={-1} className={`ve-sheet ve-ui ${collapsed?"collapsed":""}`}><header><b>{sectionLabel(selectedSection)}</b><span><button onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?"Déplier le panneau":"Réduire le panneau"}>{collapsed?"□":"—"}</button><button onClick={()=>setSelectedSection(null)} aria-label="Fermer le panneau section">×</button></span></header>{!collapsed&&<>{
  // Raccourci d'accès au média du hero depuis le panneau section — sans lui,
  // l'ajout d'un média au hero dépendait d'un clic exact sur la zone média
  // dans la page, or l'overlay visuel du hero (.hero-shade) intercepte ce
  // clic et route systématiquement vers ce panneau section (voir l'audit
  // Phase UX 2 bis, point 1). Fonctionne même quand aucun média n'existe
  // encore, puisqu'il ne dépend d'aucun élément DOM `data-media-key`.
  selectedSection==="hero"&&<div className="ve-block"><p className="ve-block-title">Média</p><button onClick={()=>setMediaMenu(heroMediaTarget(content))}>{get(content,"heroMediaId")?"🖼 Gérer le média du hero":"🖼 Ajouter un média au hero"}</button></div>
 }<div className="ve-block"><p className="ve-block-title">Section</p><div><button onClick={()=>moveSection(-1)} disabled={sectionBounds(content,selectedSection).atStart} title="Monter cette section">↟ Monter</button><button onClick={()=>moveSection(1)} disabled={sectionBounds(content,selectedSection).atEnd} title="Descendre cette section">↡ Descendre</button>{
  // La visibilité du hero est gouvernée par heroVisible (CMS classique), pas
  // par hiddenSections — "Masquer" ici n'aurait donc aucun effet réel (voir
  // l'audit Phase UX 2).
  selectedSection!=="hero"&&<button onClick={toggleSection}>{sectionIsHidden(content,selectedSection)?"👁 Afficher":"◉ Masquer"}</button>}</div><button className="ve-add-inside" onClick={()=>setAdding({after:selectedSection})}>＋ Ajouter une section ici</button></div></>}</aside>}
 {selectedLink&&linkKeys&&<aside className="ve-sheet ve-ui"><header><b>Modifier le bouton</b><button onClick={()=>setLinkKeys(null)}>×</button></header><label>Libellé<input value={selectedLink.label} onChange={e=>change(linkKeys.label,e.target.value)}/></label><label>Lien<input value={selectedLink.url} onChange={e=>change(linkKeys.url,e.target.value)}/></label></aside>}
 {galleryKey&&<aside ref={galleryPanelRef} tabIndex={-1} className="ve-gallery-panel ve-ui"><header><b>Modifier la galerie</b><button onClick={()=>setGalleryKey(null)} aria-label="Fermer le panneau galerie">×</button></header><div>{gallery.map((entry,index)=><article draggable onDragStart={()=>drag.current=index} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag.current===null)return;const next=[...gallery],moved=next.splice(drag.current,1)[0];next.splice(index,0,moved);setGallery(next)}} key={`${entry.id}-${index}`}><img src={`/api/media/${entry.id}?variant=thumbnail`} alt=""/><div className="ve-gallery-controls"><i aria-hidden="true">⋮⋮</i><button onClick={()=>{if(index===0)return;const next=[...gallery];[next[index-1],next[index]]=[next[index],next[index-1]];setGallery(next)}} disabled={index===0} aria-label="Déplacer vers le haut">↑</button><button onClick={()=>{if(index===gallery.length-1)return;const next=[...gallery];[next[index+1],next[index]]=[next[index],next[index+1]];setGallery(next)}} disabled={index===gallery.length-1} aria-label="Déplacer vers le bas">↓</button><button onClick={()=>setPicker({key:galleryKey,types:["image"],replaceIndex:index})} aria-label="Remplacer cette image">⇄</button></div><button className="ve-remove-btn" onClick={()=>setGallery(gallery.filter((_,i)=>i!==index))} aria-label="Retirer cette image">×</button><input placeholder="Alt" aria-label="Texte alternatif" value={entry.alt||""} onChange={e=>{const next=[...gallery];next[index]={...entry,alt:e.target.value};setGallery(next)}}/><input placeholder="Légende" aria-label="Légende" value={entry.caption||""} onChange={e=>{const next=[...gallery];next[index]={...entry,caption:e.target.value};setGallery(next)}}/></article>)}</div><button onClick={()=>setPicker({key:galleryKey,types:["image"]})}>＋ Ajouter des images</button></aside>}
 {adding&&<div className="ve-modal ve-ui"><div><header><h2>Ajouter une section</h2><button onClick={()=>setAdding(null)}>×</button></header><section>{sectionTypes.map(([id,label])=><button key={id} onClick={()=>addSection(id)}><i>◇</i><b>{label}</b></button>)}</section></div></div>}
 {picker&&<MediaPicker media={media} types={picker.types} multiple={Boolean(galleryKey)&&picker.replaceIndex===undefined} title={picker.replaceIndex!==undefined?"Remplacer cette image":galleryKey?"Ajouter à la galerie":"Choisir dans la bibliothèque"} close={()=>setPicker(null)} confirm={picker.replaceIndex!==undefined?replaceGalleryItem:(galleryKey?addGallery:chooseMedia)}/>}</>}
function pathParts(path:string){return path.split(".").map(part=>/^\d+$/.test(part)?Number(part):part)}function get(object:any,path:string){return pathParts(path).reduce((value,key)=>value?.[key as any],object)}function set(object:any,path:string,value:any){const next=structuredClone(object||{}),parts=pathParts(path);let cursor=next;for(let i=0;i<parts.length-1;i++){const key=parts[i],after=parts[i+1];if(cursor[key as any]==null)cursor[key as any]=typeof after==="number"?[]:{};cursor=cursor[key as any]}cursor[parts[parts.length-1] as any]=value;return next}
// Le cadrage (heroPosition) vit dans un arbre React distinct du rendu de la
// page (voir le rapport de bug) : contrairement au texte, rien ne le
// reflète automatiquement à l'écran. On applique donc le style directement
// au conteneur concerné, comme applyDom() le fait déjà pour le texte.
function applyPosition(key:string,value:string){const media=document.querySelector<HTMLElement>(`[data-position-key="${key}"] img,[data-position-key="${key}"] video`);if(media)media.style.objectPosition=value}
function applyDom(content:any){document.querySelectorAll<HTMLElement>("[data-edit-key]").forEach(node=>{const value=get(content,node.dataset.editKey!);if(value!==undefined)node.innerText=String(value)});if(content.heroPosition)applyPosition("heroPosition",content.heroPosition)}function sectionIsHidden(content:any,key:string){if(key.startsWith("chapter:")){const index=Number(key.split(":")[1]);return content.sections?.[index]?.enabled===false}if(key.startsWith("service:")||key.startsWith("team:")){const collection=key.startsWith("service:")?"services":"team",index=Number(key.split(":")[1]);return content[collection]?.[index]?.visible===false}return (content.hiddenSections||[]).includes(key)}
// La normalisation de galerie (ancien `normalizeGallery` local, dupliqué avec
// project-manager.tsx et lib/public-cms.ts) vit maintenant dans
// lib/media-normalize.ts et tolère null/undefined/entrées invalides.
