import { db, parseJson } from "./cms-db";
import { normalizeMediaList } from "./media-normalize";
export type PublicGalleryItem={id:number;hidden?:boolean;caption?:string;alt?:string};
export type PublicProject={id:number;title:string;peopleNames:string;slug:string;category:string;projectDate?:string|null;location:string;excerpt:string;description:string;coverMediaId?:number|null;gallery:PublicGalleryItem[];videos:Array<Record<string,unknown>>;tags:string[];seoTitle:string;seoDescription:string;seoImageMediaId?:number|null;featured:boolean;sections:Array<Record<string,unknown>>};
export async function setting<T>(key:string,fallback:T):Promise<T>{try{const row=await db().prepare("SELECT value FROM cms_settings WHERE key=?").bind(key).first<{value:string}>();return row?parseJson(row.value,fallback):fallback}catch{return fallback}}
export async function publishedProjects():Promise<PublicProject[]>{try{const result=await db().prepare("SELECT * FROM projects WHERE status='published' AND visible=1 AND deleted_at IS NULL ORDER BY featured DESC, display_order ASC, project_date DESC").all<Record<string,unknown>>();return Promise.all((result.results||[]).map(projectFromRow))}catch{return []}}
export async function publishedProject(slug:string,includeDraft=false):Promise<PublicProject|null>{try{const row=await db().prepare(`SELECT * FROM projects WHERE slug=? AND deleted_at IS NULL ${includeDraft?"":"AND status='published' AND visible=1"}`).bind(slug).first<Record<string,unknown>>();return row?projectFromRow(row):null}catch{return null}}
async function projectFromRow(row:Record<string,unknown>):Promise<PublicProject>{
  const sectionRows=await db().prepare("SELECT * FROM project_sections WHERE project_id=? AND enabled=1 ORDER BY display_order ASC").bind(row.id).all<Record<string,unknown>>();
  // `includeHidden:false` reproduit le comportement historique : le public ne
  // doit jamais voir une image de galerie marquée masquée par l'admin.
  const normalize=(values:unknown)=>normalizeMediaList(parseJson<unknown[]>(values,[]),{includeHidden:false});
  return {id:Number(row.id),title:String(row.title||""),peopleNames:String(row.people_names||""),slug:String(row.slug||""),category:String(row.category||"Autre"),projectDate:row.project_date?String(row.project_date):null,location:String(row.location||""),excerpt:String(row.excerpt||""),description:String(row.description||""),coverMediaId:row.cover_media_id?Number(row.cover_media_id):null,gallery:normalize(row.gallery_json),videos:parseJson(row.videos_json,[]),tags:parseJson(row.tags_json,[]),seoTitle:String(row.seo_title||""),seoDescription:String(row.seo_description||""),seoImageMediaId:row.seo_image_media_id?Number(row.seo_image_media_id):null,featured:Boolean(row.featured),sections:(sectionRows.results||[]).map((section:Record<string,unknown>)=>({...section,media:normalize(section.media_json),videos:parseJson(section.videos_json,[])}))};
}
export async function publicServices(){try{const result=await db().prepare("SELECT * FROM services WHERE visible=1 AND deleted_at IS NULL ORDER BY display_order ASC").all();return result.results||[]}catch{return []}}
export async function publicTeam(){try{const result=await db().prepare("SELECT * FROM team_members WHERE visible=1 AND deleted_at IS NULL ORDER BY display_order ASC").all();return result.results||[]}catch{return []}}
export async function pageMetadata(pageKey:string,fallbackTitle:string,fallbackDescription:string){const seo=await setting<any>("seo",{}),page=seo.pages?.[pageKey]||{},title=page.title||fallbackTitle,description=page.description||seo.description||fallbackDescription,imageId=page.imageId||seo.openGraphMediaId;return {title:pageKey==="home"?{absolute:title}:title,description,openGraph:{title,description,...(imageId?{images:[mediaUrl(imageId,"desktop")]}:{})},twitter:{card:"summary_large_image" as const,title,description,...(imageId?{images:[mediaUrl(imageId,"desktop")]}:{})}}}
export const mediaUrl=(id:unknown,variant="desktop")=>id?`/api/media/${id}?variant=${variant}`:"";
export function displayDate(value?:string|null){if(!value)return "";return new Intl.DateTimeFormat("fr-CA",{day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(value+"T12:00:00Z"))}
